-- Refined schema update with JSONB for flexibility
ALTER TABLE IF EXISTS occurrences 
ADD COLUMN IF NOT EXISTS hour TEXT,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS located_by TEXT,
ADD COLUMN IF NOT EXISTS student_ids JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS video_urls JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS signed_doc_urls JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS attenuating_factors JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS aggravating_factors JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS measure TEXT,
ADD COLUMN IF NOT EXISTS duration_days INTEGER;
